using Tyuiu.PolyakovaAS.Sprint1.Task7.V16.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #1 | Выполнил: Полякова А С | ИСТНб-24-1";
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Спринт #1                                                               *");
Console.WriteLine("* Тема: Базовые навыки работы С#                                          *");
Console.WriteLine("* Задание #7                                                              *");
Console.WriteLine("* Вариант #16                                                             *");
Console.WriteLine("* Выполнил: Полякова А С| ИСТНб-24-1                                      *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Написать программу, которая вычисляет математическое выражение          *");
Console.WriteLine("* выражение по исходным значениям данных, вводимых пользователем.         *");
Console.WriteLine("*                       cos(x)^2                                          *");
Console.WriteLine("*                       --------                                          *");
Console.WriteLine("* z = sin(sqrt (x^2)) + 3 * x^3 - sin(sqrt(x^2 - 1))                      *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                        *");
Console.WriteLine("***************************************************************************");

double x;
Console.WriteLine("Введите исходное число:");
x = Convert.ToDouble(Console.ReadLine());

Console.WriteLine("***************************************************************************");
Console.WriteLine("* Результат                                                               *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("Ответ на выражение " + ds.Calculate(x));
Console.ReadLine();