using Tyuiu.PolyakovaAS.Sprint1.Task6.V4.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #1 | Выполнил Полякова А. С. | ИСТНб-24-1";
Console.WriteLine("*******************************************************************************");
Console.WriteLine("* Спринт #1                                                                   *");
Console.WriteLine("* Тема: Базовые навыки работы в с#                                            *");
Console.WriteLine("* Задание #7                                                                  *");
Console.WriteLine("* Вариант #4                                                                  *");
Console.WriteLine("* Выполнил Журило Никита Александрович | ИСТНБ-24-1                           *");
Console.WriteLine("*******************************************************************************");
Console.WriteLine("* Условие                                                                     *");
Console.WriteLine("* Написать программу: пользователь вводит текст. Напечатать все слова,        *");
Console.WriteLine("* содержащие удвоенное н                                                      *");
Console.WriteLine("*******************************************************************************");
Console.WriteLine("* Исходные данные:                                                            *");
Console.WriteLine("*******************************************************************************");
string value;
Console.WriteLine("Введите строку: ");
value = Convert.ToString(Console.ReadLine());
Console.WriteLine("* Результат:                                                                  *");
Console.WriteLine("*******************************************************************************");
Console.WriteLine($"Количество слов с удвоенной н = {ds.CheckDoubleN(value)}");
Console.ReadKey();